# Site settings
title: 命与运
subtitle: [阿良的空间]
keywords: 阿良
description: 算命
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhubb.com/" # 你的域名
page_no_title: "阿良的文章" # 文章无标题时默认显示内容
beian: # "备案号"
author: 阿良
email: username@gmail.com

# Build settings
permalink: /post/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins:
  - jekyll-paginate
  - jemoji

# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 工具
    directory: tools/
    icon: icon-tags
#  - page: 留言
#    directory: guestbook/
#    icon: icon-guestbook
  - page: 关于
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
links: # 链接

  - title: Google
    url: https://www.google.com/
  - title: Yandex
    url: https://yandex.com/
  - title: Ask
    url: https://www.ask.com/
  - title: Naver
    url: https://www.naver.com/
  - title: Twitter
    url: https://twitter.com/
  - title: Facebook
    url: https://www.facebook.com/

# Google Analytics
ga_track_id: UA-158901256-1            # Format: UA-xxxxxx-xx
ga_domain: www.zhubb.com             # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Code hub settings
#codehub: # 代码仓库
#  - title: Github
#    url: https://github.com/google

#valine:
#  enable: true
#  app_id:  K1rbn2Oo0YMM04VuzdLS7Nzz-gzGzoHsz
#  app_key: AAsHbwVm8ofKFJ6ghGqqrXSU
#  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
#  verify: false # Verification code
#  visitor: true
#  avatar: retro
#  placeholder: say something~~\n - 昵称 为你所要显示的评论的ID；\n - 邮箱 只有后台可见，仅供讨论过程中是否需要交流邮件而设置，请放心填写;\n - 网址 为你的评论的昵称的超链接。\n当然，以上都可以不写，评论依然会显示……
#  guest_info: nick,mail,link
#  pageSize: 10

theme: jekyll-theme-cayman